### ISSUE TITLE
Default Symfony cache not working

### ISSUE THREAD

**Issue by Sigri44** [IndraGunawan/api-rate-limit-bundle#16]
Hi,

I use this package from Symfony 4.4, and with default Symfony Cache, i have an error : 
`The path "indragunawan_api_rate_limit.cache" cannot contain an empty value, but got null.`

Symfony : 4.4
PHP : 4.4
Package : latest

Thanks.

**Comment by Kreyu** [comment]
As the errors says, `cache` cannot contain empty value. You probably used `cache: ~`, which is not valid.
If you want to use Symfony cache, then provide its service name, for example `cache.app`:

```yaml
indragunawan_api_rate_limit:
    enabled: true
    cache: cache.app
 ```
